name: Gradle Build  

on:  
  push:  
    branches:  
      - main  
  pull_request:  
    branches:  
      - main  
  workflow_dispatch:  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Check out repository  
        uses: actions/checkout@v4 # upgraded from v2  

      - name: Set up JDK 17  
        uses: actions/setup-java@v3 # upgraded from v2  
        with:  
          distribution: 'temurin' # updated from 'adopt' (new recommended distro)  
          java-version: '17'  

      - name: Build with Gradle  
        run: ./gradlew build  

      - name: Upload build artifacts  
        uses: actions/upload-artifact@v3  
        with:  
          name: vLobbyConnect  
          path: build/libs/*.jar